### ISSUE TITLE
兄弟，现在这个XX还能用吗

### ISSUE THREAD

**Issue by y78yni** [brendonjkding/brendonjkding.github.io#1]
最高支持ios几。

**Comment by brendonjkding** [comment]
> 最高支持ios几。

本体没试过
开发助手好像12点击有问题
加速器都行

**Comment by Amherst0218** [comment]
Hi Brendon,
非常感谢您之前优化的加速器，帮了很大的忙。XX的程序目前我查到是最高支持ios12，目前有支持ios13的计划吗？或者说如果我想自己优化支持ios13的话应该从哪里入手呢？谢谢

**Comment by brendonjkding** [comment]
> Hi Brendon,
> 非常感谢您之前优化的加速器，帮了很大的忙。XX的程序目前我查到是最高支持ios12，目前有支持ios13的计划吗？或者说如果我想自己优化支持ios13的话应该从哪里入手呢？谢谢

我不是XX作者我自己也不用XX所以不清楚是哪里不支持
